### PR TITLE
Adding KitQL to the sample

### PR DESCRIPTION
**Pull request by jycouet**
- [x] switch to typescript
- [x] queries, mutations, ... are typed 🚀
- [x] using stores (fully generated)
- [x] automatic SSR / client side queries
- [x] removing boilerplate
- [x] adding graphiql yoga

It's just the beginning, I think that we can go way further 😁

_Side note: I had to use pnpm as yarn 3 was not working on my side. (I don't know why ><)_

### CODE REVIEW

**Comment by ajcwebdev** [comment]
Hey @jycouet, thanks so much for taking the time to open this PR! It took me a few tries to get the project working locally and the `graphql-codegen --config ./.graphqlrc.yaml` command in particular was causing me a lot of grief until I figured out that I needed to install a few extra dependencies.

But everything is now running as expected, so I suppose I'll have to refrain from excising TypeScript like I normally would 😅. I think this can be made a bit more seamless by combining the type generation command with the command to start the dev server, so I've included a `start` script with the following command: `npm run gen && npm run dev`.

I also have a couple high level questions about the implementation. I don't have any experience with KitQL and I know you've been working on this library for a while, so forgive me for asking a few noob questions about the intent of the project:

### Q1: Do we need GraphQL Yoga inside the SvelteKit app?

I noticed you're importing `@graphql-yoga/common` in `svelte/src/routes/graphql.ts`. This makes a ton of sense for a standalone SvelteKit project, however I'm not sure this makes sense for a Redwood+SvelteKit project. This project was originally using SvelteKit to make a `fetch` request directly to the Redwood API.

Redwood's API is already bundling GraphQL Yoga as the built-in server on the `api` side. Is there a particular advantage or use case that is enabled by proxying GraphQL Yoga within the SvelteKit project instead of querying the Redwood API directly? I feel like having two different instances of Yoga running at the same time on the frontend and backend could be confusing.

### Q2: How does using KitQL differ from GraphQL Requests with SvelteKit's Fetch API?

When working with SvelteKit and GraphQL, I've found it very easy to make GraphQL queries directly from the SvelteKit app utilizing the [`fetch` API](https://kit.svelte.dev/docs/web-standards#fetch-apis) in a Svelte component that queries a SvelteKit [endpoint](https://kit.svelte.dev/docs/routing#endpoints) without needing any additional dependencies.

I'm curious how you see this library improving upon that experience and where you think KitQL really shines. I know this is still an early project that's in the works so feel free to include info on where you think KitQL will be once it reaches its full potential.

**Comment by jycouet** [comment]
> Hey @jycouet, thanks so much for taking the time to open this PR! It took me a few tries to get the project working locally and the `graphql-codegen --config ./.graphqlrc.yaml` command in particular was causing me a lot of grief until I figured out that I needed to install a few extra dependencies.

Sorry about that. 
I'm surprised that you needed to install things one by one. Normally `@kitql/all-in` should already have everything included. 🤔

> But everything is now running as expected, so I suppose I'll have to refrain from excising TypeScript like I normally would 😅. I think this can be made a bit more seamless by combining the type generation command with the command to start the dev server, so I've included a `start` script with the following command: `npm run gen && npm run dev`.

👍
An alternative that I'm usually doing is: `"prepare": "npm run gen && svelte-kit sync"`
Like this, it's generating right after installing.

> I also have a couple high level questions about the implementation. I don't have any experience with KitQL and I know you've been working on this library for a while, so forgive me for asking a few noob questions about the intent of the project:

I'm always happy to see how people see the lib and gives advices / comments. So thanks a lot already. 🙏

> ### Q1: Do we need GraphQL Yoga inside the SvelteKit app?
> I noticed you're importing `@graphql-yoga/common` in `svelte/src/routes/graphql.ts`. This makes a ton of sense for a standalone SvelteKit project, however I'm not sure this makes sense for a Redwood+SvelteKit project. This project was originally using SvelteKit to make a `fetch` request directly to the Redwood API.
> 
> Redwood's API is already bundling GraphQL Yoga as the built-in server on the `api` side. Is there a particular advantage or use case that is enabled by proxying GraphQL Yoga within the SvelteKit project instead of querying the Redwood API directly? I feel like having two different instances of Yoga running at the same time on the frontend and backend could be confusing.

I added `yoga` here only to get `graphiql`, to show that it's possible.
It's totally optional (KitQL doesn't need it) and in your case, you don't really need it as you already have yoga graphiql on your API side.
_Side node: I find it sooo cool to be able to use Yoga right or left, it's sooo easy 👌_

> ### Q2: How does using KitQL differ from GraphQL Requests with SvelteKit's Fetch API?
> When working with SvelteKit and GraphQL, I've found it very easy to make GraphQL queries directly from the SvelteKit app utilizing the [`fetch` API](https://kit.svelte.dev/docs/web-standards#fetch-apis) in a Svelte component that queries a SvelteKit [endpoint](https://kit.svelte.dev/docs/routing#endpoints) without needing any additional dependencies.
> 
> I'm curious how you see this library improving upon that experience and where you think KitQL really shines. I know this is still an early project that's in the works so feel free to include info on where you think KitQL will be once it reaches its full potential.

I started to use SvelteKit & GraphQL exactly like you and found it really easy as well 👌. (and I'm using fetch internally as well)
I think that **KitQL** is doing the extra mile bringing a bit more _magic_ with:
- **Codegen**: So that your operations are converted into stores fully typed (thx to Typescript 😉 _(FYI, I'm working on a jsdoc version too to get types & js only!)_).
- **Stores**: So you can use your data everywhere, in routes, in components. You simply compose your application. (taking care of complex navigation scenario)
- **Cache**: Per query... working by default 👍
-  **Watch & Run**: seamless generation & regeneration
- **Optimistic UI & Partial**: Already present (a bit manual, but working).

A big bump is about to happen with a lot more magic. Stay tuned 🚀🚀🚀.
My aim is to ease developers exp working on SvelteKit & GraphQL.

I'm sure that we can find some collaborations on some aspects.
Speak to you soon 👋

**Comment by ajcwebdev** [comment]
@jycouet Alright, after sitting on this for a while I've decided to just merge it and rename the repo to `redwood-kitql` with the idea of leaning heavily into KitQL and the associated Guild libraries.

I'm still interested in pursuing a more straight ahead SvelteKit integration, but I think both experiments can and should go on side by side. It's too bad @mikenikles is no longer working on [Webstone](https://github.com/WebstoneHQ/webstone), although I bet he'll find this repo interesting either way.

Also, I have done a little more TypeScript recently, I think I can reasonably tolerate it now. Which is good because the Codegen stuff sounds like the most promising avenue to pursue right now.

**Comment by jycouet** [comment]
Nice to read your message 👌
Thanks for merging.

I'm always available for an open exchange on next steps 😉 I have ideas! 😁

**Pull request merged**
